#!/bin/sh -e

cp --remove-destination /usr/local/sabakan/bin/sabakan-cryptsetup /host/usr/local/bin/sabakan-cryptsetup
cp --remove-destination /usr/local/sabakan/bin/sabactl /host/usr/local/bin/sabactl
