#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary-group: ubuntu
    groups: users, admin
    lock_passwd: false
    shell: /bin/bash
    # password = "ubuntu"
    passwd: "$6$rounds=4096$1IdWhyNg1$PXQGbjAa5OVPrKq0O2R6h3jN02RF5OowmKDYVVbKQTIwe3Pvv7wwXGKduOkaKEeO.tbe7hHjA2Zpc.9JsAN.i."
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfQ2R2DS2LgjTxs+Z27hfWF4eGH2/ymeXvvUWmc5hRgC//RVnk9b2Tcix/pALNvzUqK9nTbk2F3Gn/PziBWFDSHbhYeHBRlkctu9gInLbL+VVNWmhhPDstgrUE9I+EDAB9hm958xRBBFzzpABLB7oXxeYz8RIuuDWY8I0or9q8Z/v4ZvR+hSsQI64A45obnIdp3ak/0WgyZQYtvnLGpTowDtlxz2wpIHZy9AZa/h5WC6q032o6/SzHZva0hDnQ3q2++icT8Ugm1shRaxIz9eu25z2yItEkV3FoTODRNAwzKtrrt+MwdmCabzAzObRQREXtFghZ2TqTi1FTbkPPT/7d itest
mounts:
  - [ /dev/vdc1, /data, "vfat", "ro" ]
  - [ /dev/vdd1, /ignitions, "vfat", "ro" ]
write_files:
  - content: |
      advertise-url: http://@HOST@:10080
      allow-ips: [0.0.0.0/0]
      dhcp-bind: 0.0.0.0:67
      etcd-servers: [http://@HOST1@:2379]
      ipxe-efi-path: /boot/ipxe.efi
    path: /etc/sabakan.yml
    permissions: '0644'
packages:
  - grub-ipxe
