name: release
on:
  push:
    tags:
      - 'v*'
env:
  tag: ${GITHUB_REF#refs/tags/v}
  prerelease: ${{ contains(github.ref, '-') }}
jobs:
  release-image:
    name: Release Sabakan Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup golang
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Build image
        run: make docker-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container image
        run: |
          echo "pushing Sabakan image ..."
          docker tag ghcr.io/cybozu-go/sabakan:latest ghcr.io/cybozu-go/sabakan:${{ env.tag }}
          docker push ghcr.io/cybozu-go/sabakan:${{ env.tag }}
          if ${{ env.prerelease }} ; then
              echo ===== Skip pushing branch tags for pre-release ${{ env.tag }} =====
              exit 0
          fi
          BRANCH=$(echo ${{ env.tag }} | cut -d "." -f 1-2)
          docker tag ghcr.io/cybozu-go/sabakan:latest ghcr.io/cybozu-go/sabakan:$BRANCH
          docker push ghcr.io/cybozu-go/sabakan:$BRANCH

  release-github:
    name: Release GitHub
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=v${{ env.tag }}
          if ${{ env.prerelease }}; then PRERELEASE_FLAG=-p; fi
          gh release create $VERSION $PRERELEASE_FLAG \
            -t "Release $VERSION"  \
            -n "See [CHANGELOG.md](./CHANGELOG.md) for details."
